/**
 * Gebiedsinformatie voor de AI-chatwidget.
 *
 * Gebruikt door chat.js als kennisbasis voor gebiedsvragen:
 * "Wat is [gebied] zo?", "Vergelijk Estepona met Marbella", "Waar past een
 * gezin met kinderen het best?", etc.
 *
 * Bronnen: engelvoelkers.com, dmproperties.com, marbella-estates.com,
 * idealista.com/news, theolivepress.es, sotograndeguide.com,
 * dolanproperty.es, starlacala.com, niche-estates.com (zomer 2026).
 * Prijzen zijn indicatief en gebaseerd op marktdata 2024–2026.
 *
 * Update dit bestand als marktcondities sterk wijzigen (>10% prijsshift
 * of nieuwe infrastructuur). Prijsranges zijn voor nieuwbouw tenzij anders
 * vermeld.
 */

const AREAS = {
  estepona: {
    name: 'Estepona',
    slug: 'estepona',
    karakter: 'Estepona is een charmante kuststadjes met een authentiek Andalusisch hart: witte gevels, bloemrijke straatjes en een levendige vissersboulevard. Het is de afgelopen jaren uitgegroeid tot een van de populairste plekken op de Costa del Sol dankzij zware stedelijke investeringen — maar zonder het massa-toerisme van Marbella. De sfeer is gezinsvriendelijk, internationaal maar niet opzichtig, en het hele jaar door actief.',
    ligging: {
      malaga_airport_km: 90,
      malaga_airport_min: 60,
      marbella_centrum_km: 30,
      marbella_centrum_min: 30,
      strand_min: '2–10 minuten afhankelijk van de wijk',
      golf: 'Meer dan 10 golfbanen in de directe omgeving (Valle Romano, Estepona Golf, El Paraiso, Atalaya)',
      bijzonderheden: 'Aansluiting op de A-7/AP-7 snelweg; nieuwe rondweg ontlast het centrum',
    },
    doelgroep: [
      'Gezinnen die full-time willen emigreren of frequent terugkeren',
      'Kopers 45–65 die authentiek Spaans leven zoeken naast strandcomfort',
      'Investeerders die instappen voor de waardestijging (nieuwe projecten, lager instapniveau dan Marbella)',
      'Golfers (ruim aanbod banen)',
      'Nederlanders en Belgen: Estepona is hun #1 keuzegebied op de Costa del Sol',
    ],
    prijsniveau: {
      segment: 'midden tot luxe',
      prijs_per_m2_range: '€3.000 – €5.500/m²',
      typisch_appartement: '€250.000 – €550.000',
      typische_villa: '€700.000 – €3.000.000',
      toelichting: 'Duidelijk goedkoper dan Marbella (Golden Mile), maar goedkopere instapprojecten in Cancelada of Valle Romano vanaf €200.000. Nieuwbouw New Golden Mile zit in het midden-luxe segment.',
    },
    troeven: [
      'Sterk stijgende vastgoedwaarden (+8–10%/jaar), nog groeipotentieel t.o.v. Marbella',
      'Authentieke Spaanse sfeer met bloemenstraatjes en levendig stadscentrum',
      'Groot nieuwbouwaanbod: veel keuze in types en prijsklassen',
      'Uitstekende infrastructuur: nieuwe ziekenhuisvleugel, internationale scholen, grote supermarkten',
      'New Golden Mile: rustige luxestrip direct aan zee tussen Estepona en San Pedro',
      'Populair bij NL/BE kopers: groot expat-netwerk aanwezig',
    ],
    aandachtspunten: [
      'Verder van Málaga airport dan Marbella of Mijas (~60 min vs. ~45 min)',
      'Sommige nieuwbouwwijken (bv. Valle Romano) liggen 3–5 km van strand en centrum — auto onmisbaar',
      'In hoogseizoen kan het centrum druk worden, maar niet vergelijkbaar met Torremolinos/Benalmádena',
    ],
    verhuurpotentieel: 'Sterk: toeristisch aantrekkelijk, hoge bezetting in zomer. Korte termijn verhuur €1.200–€3.500/week in hoogseizoen voor 2-slaapkamerappartement. Jaarlijkse huurrendementen 4–6% bruto. Vergunningplicht voor toeristische verhuur.',
    infrastructuur: 'Volledig uitgerust: Mercadona, Carrefour, El Corte Inglés (vlakbij), internationaal ziekenhuis (Quirón Estepona), Laude en SotoReal internationale scholen, tientallen restaurants, strand promenade, wekelijkse markt.',
  },

  marbella: {
    name: 'Marbella',
    slug: 'marbella',
    karakter: 'Marbella is het prestige-adres van de Costa del Sol: glamoureus, internationaal en het hele jaar door actief. De Golden Mile ademt exclusiviteit met villacomplexen, hotels en boutiquerestaurants. Nueva Andalucía is de "Golf Valley" met golfresorts en gezinsvriendelijke urbanisaties. Oost-Marbella (Elviria, Los Monteros) is rustiger, weelderig groen en dichtbij de stad. Marbella spreekt iedereen aan van celebrities tot pensionado\'s die kwaliteit en status hoog in het vaandel dragen.',
    ligging: {
      malaga_airport_km: 60,
      malaga_airport_min: 45,
      marbella_centrum_km: 0,
      strand_min: '1–15 minuten afhankelijk van zone',
      golf: 'Golf Valley / Nueva Andalucía: dichtstbijzijnde concentratie golfbanen ter wereld (Aloha, Las Brisas, Los Naranjos, La Quinta...)',
      bijzonderheden: 'Puerto Banús op 5 min van Golden Mile; Marbella centrum met Oude Stad en Oranjeplein',
    },
    doelgroep: [
      'Vermogende kopers 50+ die prestige en kwaliteit zoeken',
      'Golfers (Nueva Andalucía = Golf Valley)',
      'Internationale investeerders (hoog liquiditeitsmarkt)',
      'Gezinnen met hoog budget die internationale scholen en fulltime luxe dienstverlening willen',
      'Tweede verblijf voor mensen die ook in andere luxe-bestemmingen kopen',
    ],
    prijsniveau: {
      segment: 'luxe tot ultra-luxe',
      prijs_per_m2_range: '€4.500 – €12.000/m² (Golden Mile tot €20.000+/m²)',
      typisch_appartement: '€600.000 – €2.000.000 (Golden Mile/Nueva Andalucía)',
      typische_villa: '€2.000.000 – €20.000.000+',
      toelichting: 'Duurste regio van de Costa del Sol. Elviria/Marbella Oost is relatief betaalbaarder (vanaf €350.000 voor appartement). Golden Mile frontline villa\'s halen €30.000+/m². Marktgroei 2024–2025: +13–20% j/j.',
    },
    troeven: [
      'Meest gevestigde luxemarkt op de Costa del Sol met sterke prijsappreciatie',
      'Puerto Banús: iconische jachthaven met high-end winkels en restaurants',
      'Golf Valley (Nueva Andalucía): beste golfinfrastructuur van Europa',
      'Uitstekende internationale scholen (Aloha College, English International College)',
      'Topmedische zorg: Hospital Quirónsalud Marbella, kliniek Costa del Sol',
      'Jaar-rond bruisend socio-cultureel leven',
    ],
    aandachtspunten: [
      'Hoogste prijsniveau van de Costa del Sol — nieuwbouwaanbod beperkt door weinig beschikbare grond',
      'Verkeersopstoppingen in zomer langs de N-340 en in centrum',
      'Toeristische druk in hoogseizoen (ook voordeel voor verhuur, nadeel voor rustige bewoning)',
    ],
    verhuurpotentieel: 'Uitstekend: hoogste huurprijzen op de Costa del Sol. Golden Mile villa €15.000–€50.000/week in hoogseizoen. Appartementen Nueva Andalucía €1.500–€4.000/week. Langetermijnhuur sterk door internationale gemeenschap. Toeristische verhuurvergunning vereist.',
    infrastructuur: 'Beste infrastructuur van de regio: El Corte Inglés, internationale supermarkten, toprestaurants, jachthavens, Beach Clubs (Nikki Beach, Ocean Club), 3 ziekenhuizen, tientallen internationale scholen, 5-sterrenhotels.',
  },

  benahavis: {
    name: 'Benahavís',
    slug: 'benahavis',
    karakter: 'Benahavís is een van de meest exclusieve gemeenten van Spanje: bijna geen doorgaand toerisme, enkel privé-resorts en gated communities in de heuvels boven Marbella. La Quinta is het paradepaardje: groene bergen, panoramische zeezichten en een wereldklasse golfbaan. De sfeer is discreet, groen en absoluut privaat. Het dorp zelf (Pueblo Benahavís) is klein en Andalusisch authentiek, bekend om zijn restaurants.',
    ligging: {
      malaga_airport_km: 72,
      malaga_airport_min: 55,
      marbella_centrum_km: 12,
      marbella_centrum_min: 15,
      strand_min: '15–20 minuten (Puerto Banús is het dichtstbij)',
      golf: 'La Quinta Golf & Country Club direct aangrenzend; diverse andere banen op 10–20 min',
      bijzonderheden: 'Gelegen in de bergen boven San Pedro; alleen bereikbaar via smalle bergwegen — rustig en privaat',
    },
    doelgroep: [
      'Ultra-vermogende kopers die privacy en exclusiviteit boven alles stellen',
      'Golfers die op een golfresort willen wonen',
      'Internationale investeerders (84% kopers zijn buitenlanders)',
      'Kopers die gezichtsbepalende zeezichten én bergpanorama willen combineren',
    ],
    prijsniveau: {
      segment: 'luxe tot ultra-luxe',
      prijs_per_m2_range: '€3.500 – €8.000/m²',
      typisch_appartement: '€600.000 – €2.000.000',
      typische_villa: '€2.500.000 – €15.000.000+',
      toelichting: 'La Zagaleta (aangrenzend, ook Benahavís) is de duurste gated community van Europa met villa\'s tot €50M. La Quinta is luxe maar iets toegankelijker. Gemiddelde transactieprijs ~€3,2M.',
    },
    troeven: [
      'Absolute privacy: geen doorgaand verkeer, enkel bewoners en gasten in gated communities',
      'Indrukwekkende panoramische uitzichten over zee én bergen',
      'La Quinta Golf: een van de mooiste golfterreinen van de Costa del Sol',
      'Slechts 15 minuten van Marbella centrum en Puerto Banús',
      'Laagste bebouwingsdichtheid van de regio: veel groen, frisse lucht',
      'Pueblo Benahavís: authentiek Andalusisch met uitstekende restaurants',
    ],
    aandachtspunten: [
      'Strand is 15–20 minuten rijden — minder geschikt voor dagelijks strandbezoek',
      'Auto absoluut onmisbaar: geen openbaar vervoer in de heuvels',
      'Beperkt aanbod nieuwbouw — wanneer iets beschikbaar is, gaat het snel',
    ],
    verhuurpotentieel: 'Goed maar nichemarkt: huurders voor ultra-luxe villa\'s zijn minder talrijk maar betalen top. Villaverhuur €10.000–€40.000/week. Toeristische verhuurvergunning vereist; hogere bezettingsgraad in zomer.',
    infrastructuur: 'Beperkt in het dorp zelf (klein Andalusisch dorpje). Alle faciliteiten in San Pedro of Marbella (15 min). Gated communities hebben eigen security, zwembaden en soms clubhuis/restaurant. Pueblo Benahavís: gekend om zijn restaurants.',
  },

  'san-pedro': {
    name: 'San Pedro de Alcántara',
    slug: 'san-pedro',
    karakter: 'San Pedro de Alcántara is Marbella\'s rustigere zusje aan de westkant: een echte Spaanse stad met een levendig centrum, brede boulevard en een sterk gevoel van buurtleven. Het trekt een mix van Spanjaarden, expats en internationale gezinnen aan die de luxe van Marbella willen zonder het drukte en het prijskaartje. De afgelopen jaren is het sterk geüpgraded met nieuwe restaurants, winkels en een vernieuwde strandpromenade.',
    ligging: {
      malaga_airport_km: 72,
      malaga_airport_min: 55,
      marbella_centrum_km: 11,
      marbella_centrum_min: 12,
      strand_min: '5–10 minuten',
      golf: 'Benahavís golfbanen 10–15 min; Atalaya Golf op 5 min',
      bijzonderheden: 'Vlakbij afrit snelweg AP-7; goed verbonden met Marbella en Estepona',
    },
    doelgroep: [
      'Gezinnen die full-time wonen (uitstekende internationale scholen)',
      'Kopers 45–60 die authentiek Spaans leven combineren met makkelijke bereikbaarheid',
      'Tweeverdieners die dicht bij Marbella maar goedkoper willen wonen',
      'Golfers: nabij Benahavís Golf Valley',
    ],
    prijsniveau: {
      segment: 'midden tot midden-hoog',
      prijs_per_m2_range: '€4.000 – €6.500/m²',
      typisch_appartement: '€300.000 – €800.000',
      typische_villa: '€800.000 – €3.000.000',
      toelichting: 'Goedkoper dan Marbella centrum, duurder dan Estepona. Stijgt stevig: +7% in 2024. Linda Vista en Nueva Alcántara zijn de meest gegeerde subwijken. San Pedro International College en Laude zijn nabij.',
    },
    troeven: [
      'Echte Spaanse stad met eigen identiteit: markt, tapasbar, lokale bevolking',
      'Vernieuwde strandpromenade met chiringuitos en beach clubs',
      'Centrale ligging: Marbella en Estepona allebei op 15–20 min',
      'Uitstekende internationale scholen (Calpe, Laude, San Pedro International College)',
      'Goede prijs-kwaliteitsverhouding ten opzichte van Marbella',
      'Sterk groeiende restaurantscène',
    ],
    aandachtspunten: [
      'Minder glamoureus imago dan Marbella — sommige kopers vinden het te "gewoon"',
      'Centrumstraten druk in zomer, parkeerproblemen',
      'Sommige oudere wijken zijn minder onderhouden — kies wijk bewust',
    ],
    verhuurpotentieel: 'Solide: goed strandaanbod, dicht bij Marbella. Appartementen strand €1.200–€2.500/week in zomer. Langdurige huurmarkt sterk door internationale gezinnen. Rendement ~4–5% bruto.',
    infrastructuur: 'Goed uitgerust: Mercadona, Carrefour, lokale markt, diverse internationale scholen, kliniek, restaurants en beach clubs. Ziekenhuis Marbella op 12 min.',
  },

  cancelada: {
    name: 'Cancelada',
    slug: 'cancelada',
    karakter: 'Cancelada is een klein Andalusisch dorp dat zich stilaan heeft omringd met nieuwe residentiële projecten, gelegen op de New Golden Mile tussen Estepona en San Pedro. Het heeft een lokale kroeg, een wekelijkse markt en een rustige dorpssfeer — maar wordt omringd door luxenieuwe bouwprojecten die van de gunstige ligging vlakbij het strand profiteren. Het is een hybride gebied: authentiek dorp én groeiende woonwijk.',
    ligging: {
      malaga_airport_km: 80,
      malaga_airport_min: 55,
      marbella_centrum_km: 20,
      marbella_centrum_min: 20,
      strand_min: '5–12 minuten (afhankelijk van de specifieke locatie)',
      golf: 'Atalaya Golf op 5 min, Villa Padierna Golf op 10 min',
      bijzonderheden: 'Aan de N-340 en AP-7; onderdeel van de "New Golden Mile" strook',
    },
    doelgroep: [
      'Kopers met een budget van €200.000 – €500.000 die nog in het New Golden Mile gebied willen kopen',
      'Gezinnen die ruimte, rust én strandnabijheid combineren',
      'Investeerders die vroeg instappen voor waardestijging in de New Golden Mile zone',
    ],
    prijsniveau: {
      segment: 'midden (goedkoper dan Estepona centrum)',
      prijs_per_m2_range: '€2.800 – €4.200/m²',
      typisch_appartement: '€200.000 – €500.000',
      typische_villa_townhouse: '€400.000 – €900.000',
      toelichting: 'Instapprijs van de New Golden Mile zone: iets inland, maar goed bereikbaar strand. Lager dan Estepona centrum of San Pedro. Goede waarde voor de ligging.',
    },
    troeven: [
      'Beste prijs-ligging verhouding van de New Golden Mile: strand en golf op 5–10 min',
      'Rustig en authentiek karakter met lokaal gemeenschap',
      'Groeiende nieuwe projecten bieden moderne woningen aan lagere prijzen dan Estepona centrum',
      'Nabij Villa Padierna Hotel (5-sterren) verhoogt prestige van de omgeving',
    ],
    aandachtspunten: [
      'Auto absoluut nodig: weinig op wandelafstand vanuit het nieuwbouwgebied zelf',
      'Minder bekende naam dan Estepona of Marbella — lagere wederverkoopwaarde op korte termijn',
      'Beperkte eigen horeca en winkels in het dorp zelf',
    ],
    verhuurpotentieel: 'Goed: ligging op New Golden Mile trekt toeristen. Appartementen €800–€2.000/week. Iets lager dan Estepona centrum of strandlocaties, maar goede bezettingsgraad.',
    infrastructuur: 'Beperkt in het dorp zelf: lokale supermarkt, bar-restaurant. Alles op 10–15 min: Mercadona Estepona, internationale scholen, ziekenhuis, strand. Atalaya Golf op 5 min.',
  },

  casares: {
    name: 'Casares (Golf / Costa)',
    slug: 'casares',
    karakter: 'Casares is een dubbel gebied: het prachtige witte bergdorp (Casares Pueblo, een van de mooiste van Andalusië) en de kustzone (Casares Costa) met nieuwbouwprojecten dicht bij het strand. Het is een opkomende bestemming die nog betaalbaar is maar dicht bij Estepona en met direct strandzicht of golfligging. De sfeer is rustig en naturel, ver van toeristische drukte.',
    ligging: {
      malaga_airport_km: 110,
      malaga_airport_min: 70,
      marbella_centrum_km: 45,
      marbella_centrum_min: 40,
      gibraltar_km: 35,
      gibraltar_min: 30,
      strand_min: '2–10 minuten (Casares Costa)',
      golf: 'Finca Cortesín Golf (een van de beste van Spanje) op 5 min; Alcaidesa en Valle Romano op 20 min',
      bijzonderheden: 'Grens met gemeente Manilva; gemeente overspant van kust tot bergdorp',
    },
    doelgroep: [
      'Kopers met een budget €200.000 – €600.000 die instapprijs en groeipotentieel zoeken',
      'Rustzoekers: natuur, rust, kleine gemeenschap',
      'Golfers: Finca Cortesín (een van de top-3 golfbanen van Spanje) vlakbij',
      'Investeerders die vroeg in een opkomend gebied willen stappen',
    ],
    prijsniveau: {
      segment: 'budget tot midden',
      prijs_per_m2_range: '€2.500 – €4.000/m²',
      typisch_appartement: '€180.000 – €500.000',
      typische_villa: '€500.000 – €1.500.000',
      toelichting: 'Een van de goedkoopste kustgebieden van de Costa del Sol. Significant lager dan Estepona. Stijgende markt: +8% j/j in 2024. Finca Cortesín-omgeving heeft premium Villa-prijzen.',
    },
    troeven: [
      'Finca Cortesín Golf: een van de mooiste banen ter wereld (host van Ryder Cup 2031)',
      'Laagste instapprijzen van de gehele Costa del Sol voor strandnabij nieuwbouw',
      'Sterke waardestijging verwacht nu West Costa del Sol terrein wint',
      'Casares Pueblo: prachtig wit bergdorp, spectaculaire uitzichten',
      'Rustige omgeving ver van toeristische massa',
    ],
    aandachtspunten: [
      'Verst van Málaga airport op de westelijke Costa (70+ min)',
      'Beperkte eigen infrastructuur in Casares Costa: voor winkels en restaurants naar Estepona of Manilva',
      'Minder gekend bij huurders: korte termijn verhuurmarkt kleiner dan in Marbella/Estepona',
    ],
    verhuurpotentieel: 'Groeiend maar nog bescheiden. Golfers dankzij Finca Cortesín een specifieke niche. Appartementen €700–€1.500/week in hoogseizoen. Langetermijnhuur beperkt door kleine expat-gemeenschap.',
    infrastructuur: 'Beperkt ter plaatse. Casares Costa: supermarkt, enkele restaurants. Estepona op 15 min voor volledig aanbod. Pueblo Casares: kleinschalig, toeristisch op weekends.',
  },

  manilva: {
    name: 'Manilva',
    slug: 'manilva',
    karakter: 'Manilva is het budgetvriendelijkste kustgebied van de Costa del Sol: authentiek, relaxt en met een eigen karakter ver van het toeristische geweld. Puerto de la Duquesa is de jachthaven van Manilva — gezellig, kleinschalig en populair bij vissers en expats. Het gebied is populair bij Britten (nabijheid van Gibraltar) en groeit gestaag. Ideaal voor wie maximale waarde voor het geld zoekt en dicht bij Gibraltar wil zitten.',
    ligging: {
      malaga_airport_km: 105,
      malaga_airport_min: 70,
      marbella_centrum_km: 42,
      marbella_centrum_min: 38,
      gibraltar_km: 20,
      gibraltar_min: 20,
      strand_min: '2–10 minuten',
      golf: 'Valle Romano en Estepona Golf op 20–25 min; Finca Cortesín op 15 min',
      bijzonderheden: 'Puerto de la Duquesa: kleine gezellige jachthaven; blauwe-vlag stranden',
    },
    doelgroep: [
      'Kopers met budget tot €400.000 die strand én zon willen zonder hoge prijzen',
      'Britse kopers die nabij Gibraltar willen wonen (werken of zakendoen in Gibraltar)',
      'Pensionado\'s die rust en betaalbaarheid combineren',
      'Investeerders die laag instappen en profiteren van waardestijging',
    ],
    prijsniveau: {
      segment: 'budget',
      prijs_per_m2_range: '€2.000 – €3.500/m²',
      typisch_appartement: '€130.000 – €400.000',
      typische_villa: '€350.000 – €900.000',
      toelichting: 'Goedkoopste kustgebied van de Costa del Sol (Málaga-provincie). Forse stijging: van €2.331/m² in 2022 naar €3.000/m² in 2024 (+18%). Laagste instapniveau, grootste groeipotentieel procentueel.',
    },
    troeven: [
      'Laagste prijzen van de Costa del Sol: maximale waarde voor het geld',
      'Puerto de la Duquesa: gezellige jachthaven met restaurants en vissersboten',
      'Nabij Gibraltar Airport (20 min): extra vluchtopties voor Britse kopers',
      'Blauwe vlag stranden, rustige kustlijn',
      'Sterk stijgende markt: +18% prijsstijging in 2 jaar',
      'Laag toeristisch volume: rustiger wonen dan Torremolinos of Fuengirola',
    ],
    aandachtspunten: [
      'Verst van Málaga airport (70+ min): minder praktisch voor wekelijks pendelende kopers',
      'Beperkte eigen voorzieningen: grotere supermarkten en ziekenhuis zijn 20–30 min weg',
      'Minder internationale aantrekkingskracht voor korte termijn verhuur vergeleken met Marbella/Estepona',
    ],
    verhuurpotentieel: 'Groeiend: 4–6% bruto rendement. Jachthaven en strand trekken zomervakantiegasten. Appartementen €600–€1.200/week. Britten die bij Gibraltar werken zorgen voor stabiele langetermijnhuurmarkt.',
    infrastructuur: 'Beperkt maar functioneel: lokale supermarkt, apotheek, medische post. Puerto de la Duquesa: restaurants, café\'s, aanlegsteiger. Estepona op 20 min voor volledig aanbod. Geen eigen ziekenhuis.',
  },

  alcaidesa: {
    name: 'La Alcaidesa',
    slug: 'alcaidesa',
    karakter: 'La Alcaidesa is een rustige, exclusieve residentiële zone tussen Gibraltar en Sotogrande — een van de best bewaarde geheimen van de westelijke Costa del Sol. Het biedt spectaculaire panoramische uitzichten over de Middellandse Zee, Gibraltar en de Afrikaanse kust. De zone heeft twee topgolfbanen en het nieuwe Fairmont La Hacienda resort (geopend 2025) maakt het definitief een luxury bestemming. Rust, natuur en grandeur.',
    ligging: {
      malaga_airport_km: 115,
      malaga_airport_min: 80,
      gibraltar_airport_km: 15,
      gibraltar_airport_min: 20,
      marbella_centrum_km: 60,
      marbella_centrum_min: 50,
      strand_min: '5–15 minuten',
      golf: 'Alcaidesa Links en Alcaidesa Heathland direct aangrenzend; Sotogrande Real Golf op 15 min',
      bijzonderheden: 'Grens Cádiz-Málaga; technisch in gemeente San Roque (Cádiz)',
    },
    doelgroep: [
      'Golfers die op een links-golfbaan met zeezicht willen wonen',
      'Kopers die Sotogrande kwaliteit zoeken aan instapprijs',
      'Britse kopers die Gibraltar Airport (20 min) verkiezen',
      'Rustzoekers en natuur-liefhebbers',
    ],
    prijsniveau: {
      segment: 'midden tot luxe',
      prijs_per_m2_range: '€3.000 – €6.000/m²',
      typisch_appartement: '€350.000 – €800.000',
      typische_villa: '€800.000 – €3.000.000',
      toelichting: 'Duidelijk goedkoper dan Marbella, vergelijkbaar of goedkoper dan Sotogrande voor vergelijkbare producten. Nieuwe ontwikkelingen 2025-2026 geprijsd tussen €549.000 en €1.245.000. Sterk stijgende vraag.',
    },
    troeven: [
      'Unieke zeezichten op Gibraltar, Marokko en de Middellandse Zee',
      'Twee topgolfbanen direct aangrenzend (Alcaidesa Links en Heathland)',
      'Fairmont La Hacienda: nieuw 5-sterren luxeresort (2025) verhoogt de omgevingswaarde',
      'Rustig en privaat: geen massa-toerisme',
      'Gibraltar Airport op 20 min: directe vluchten naar UK en Europa',
      'Nog betaalbaarder dan Sotogrande met vergelijkbaar uitzicht',
    ],
    aandachtspunten: [
      'Ver van Málaga airport (80 min): overweeg Gibraltar Airport als alternatief',
      'Kleinschalige gemeenschap: weinig eigen winkels of restaurants ter plaatse',
      'Sotogrande heeft meer uitgebreide infrastructuur voor dagelijks leven',
    ],
    verhuurpotentieel: 'Nichemart maar groeiend: golf- en resort-toerisme. Appartementen €900–€2.000/week. Fairmont resort nabijheid zal kortetermijnverhuur verder stimuleren. Langetermijnhuur voor Gibraltar-werknemers is sterk.',
    infrastructuur: 'Beperkt ter plaatse. Sotogrande Pueblo op 10 min voor restaurants en basisdiensten. La Línea / Algeciras voor volledig aanbod en ziekenhuis. Gibraltar op 20 min voor Brits winkelen en diensten.',
  },

  sotogrande: {
    name: 'Sotogrande',
    slug: 'sotogrande',
    karakter: 'Sotogrande is het "Monaco van Spanje": een besloten luxe-enclave met de grootste privé-jachthaven van Andalusië, de beste poloclub van Europa (Real Club de Polo) en een van de topgolfbanen ter wereld (Valderrama, host van de Ryder Cup). De sfeer is discreet, internationaal en aristocratisch — geen opzichtigheid maar stille rijkdom. Sotogrande trekt Britse, Zweedse en internationale elite-families die jaar-rond of in de zomer verblijven. Strikt residentieel, weinig toerisme.',
    ligging: {
      malaga_airport_km: 130,
      malaga_airport_min: 90,
      gibraltar_airport_km: 25,
      gibraltar_airport_min: 30,
      marbella_centrum_km: 65,
      marbella_centrum_min: 55,
      strand_min: '5–20 minuten afhankelijk van de wijk',
      golf: 'Valderrama, La Reserva, Real Club de Golf Sotogrande — allemaal ter plaatse',
      bijzonderheden: 'Technisch in provincie Cádiz (niet Málaga) — andere belastingregels soms van toepassing',
    },
    doelgroep: [
      'Ultra-vermogende families die maximale privacy en exclusiviteit zoeken',
      'Polo- en golfliefhebbers (beste infrastructuur ter wereld)',
      'Internationale elite met kinderen op de Sotogrande International School (topscore IB)',
      'Langetermijn residenten die het lifestyle-concept van een private resort-gemeenschap willen',
    ],
    prijsniveau: {
      segment: 'ultra-luxe',
      prijs_per_m2_range: '€3.500 – €9.000/m² (plus La Reserva tot €15.000+/m²)',
      typisch_appartement: '€600.000 – €2.000.000',
      typische_villa: '€2.000.000 – €30.000.000+',
      toelichting: 'Gemiddelde transactieprijs steeg naar €1,9M in 2024 (+30% in 1 jaar). La Reserva Club residences zijn de duurste. Vergeleken met Marbella Golden Mile nog "relatief" betaalbaar voor vergelijkbare oppervlakte en privacy.',
    },
    troeven: [
      'Beste polo-infrastructuur van Europa: Real Club de Polo en meerdere veldbanen',
      'Valderrama: een van de 10 beste golfbanen ter wereld',
      'Sotogrande International School: topscore IB-programma van kleuter tot hoger onderwijs',
      'Grootste privé-jachthaven van Andalusië',
      'Absolute privacy: private wegen, 24/7 beveiliging, geen doorgaand verkeer',
      'Uniek: natuur van het Alcornocales-park direct aangrenzend',
    ],
    aandachtspunten: [
      'Verst van Málaga airport op de Costa: 90 min — maar Gibraltar Airport op 30 min',
      'Buiten het hoogseizoen kan het erg rustig (verlaten) aanvoelen: 80% van huizen zijn zomerverblijf',
      'In provincie Cádiz (niet Málaga): controleer belastingregimes voor Andalusische subsidies',
    ],
    verhuurpotentieel: 'Sterk maar nichemarkt: polo-gerelateerde huurders in zomer tot €50.000/week voor grote villa\'s. Jaarlijkse huurrendementen lager dan Marbella door minder toerisme. Langetermijnhuur voor expat-schoolgezinnen sterk (Sotogrande International School).',
    infrastructuur: 'Uitstekend binnen de gemeenschap: Sotogrande International School, Pueblo Nuevo met restaurants en winkels, medisch centrum, privé-zeiljacht- en poloclub. Ziekenhuis in Algeciras (15 min) en Gibraltar (30 min).',
  },

  mijas: {
    name: 'Mijas (Costa, Pueblo & La Cala)',
    slug: 'mijas',
    karakter: 'Mijas is eigenlijk drie plekken in één gemeente. Mijas Pueblo is het schilderachtige witte bergdorp op 400m hoogte — toeristisch maar authentiek. Mijas Costa is de brede kuststrook met strandwijken als Calahonda, La Cala de Mijas en Riviera del Sol — internationaal, golf-georienteerd en gezinsvriendelijk. La Cala de Mijas is het bruisendste centrum van Mijas Costa: een klein strandstadje met een bloeiende internationale gemeenschap. Het geheel spreekt een breed publiek aan van golfers tot gezinnen.',
    ligging: {
      malaga_airport_km: 30,
      malaga_airport_min: 25,
      marbella_centrum_km: 30,
      marbella_centrum_min: 30,
      strand_min: '2–10 minuten (Mijas Costa / La Cala)',
      golf: '10+ golfbanen binnen 15 minuten: La Cala Golf Resort, Miraflores, Torrequebrada...',
      bijzonderheden: 'Halverwege Málaga en Marbella; snelle luchthavenbereikbaarheid is groot voordeel',
    },
    doelgroep: [
      'Gezinnen met kinderen (internationale scholen, strand, natuur)',
      'Golfers: La Cala Golf Resort (3 banen) is een van de beste golfresorst van Europa',
      'Kopers die dichtbij Málaga airport willen zitten',
      'Investeerders met oog op toeristische verhuur: sterke toeristenstroom door centrale ligging',
      'Nederlanders en Belgen: Mijas Costa staat in hun top-3 koopgebieden',
    ],
    prijsniveau: {
      segment: 'midden',
      prijs_per_m2_range: '€3.000 – €5.500/m²',
      typisch_appartement: '€250.000 – €700.000',
      typische_villa: '€700.000 – €3.000.000',
      toelichting: 'La Cala de Mijas: median €4.469/m² voor appartementen (2025). Mijas Costa gemiddeld €4.104/m² (+12% j/j). Riviera del Sol goedkoper instapgebied. Mijas Pueblo heeft goedkoper woonaanbod maar beperkt nieuwbouw.',
    },
    troeven: [
      'Dichtste Costa del Sol-gebied bij Málaga airport: slechts 25 minuten',
      'La Cala Golf Resort: een van Europas beste golfresorsts (3 banen, hotel, spa)',
      'Breed scala aan eigendommen voor verschillende budgetten',
      'La Cala de Mijas: bruisend internationaal centraaltje met goede restaurants',
      'Mooie balans tussen natuur en kustleven',
      '+12% prijsstijging in 2024–2025: sterke waardegroei',
    ],
    aandachtspunten: [
      'Mijas Costa is erg uitgestrekt: La Cala en Calahonda liggen ver uit elkaar — kies buurt bewust',
      'Minder glamoureus dan Marbella of Estepona: een back-to-basics kustleven',
      'Mijas Pueblo heeft slechts 15 min maar is heel anders van karakter dan de kust',
    ],
    verhuurpotentieel: 'Uitstekend: centrale ligging en golftoerisme. La Cala appartementen €1.000–€2.500/week. Golf-villa\'s hoger. Bruto rendement 5–7%. Een van de populairste verhuurgebieden voor NL/BE investeerders.',
    infrastructuur: 'Goed in La Cala: supermarkten, restaurants, apotheek, internationale scholen (Aloha College, Laude op 20 min). Medisch centrum in La Cala; ziekenhuizen in Marbella en Fuengirola op 20 min.',
  },

  fuengirola: {
    name: 'Fuengirola',
    slug: 'fuengirola',
    karakter: 'Fuengirola is de meest levensvatbare en internationale kuststad van de Costa del Sol: ~80.000 inwoners het hele jaar door, een bruisend stadscentrum, een lange strandpromenade en een sterk Scandinavisch expat-netwerk. Het is geen rustig pensioendorp maar een echte stad met drukte, stedelijkheid en alles op wandelafstand. Betaalbaarder dan Marbella maar met verrassend goede voorzieningen. Populair bij kopers die urban comfort zoeken in de zon.',
    ligging: {
      malaga_airport_km: 28,
      malaga_airport_min: 20,
      marbella_centrum_km: 35,
      marbella_centrum_min: 35,
      strand_min: '2–5 minuten',
      golf: 'Torrequebrada Golf op 10 min; Mijas Golf op 20 min',
      bijzonderheden: 'Treinstation (Cercanías): directe verbinding Málaga centrum en airport in 25 min',
    },
    doelgroep: [
      'Kopers die urban coastal living willen: restaurants, winkels, evenementen op wandelafstand',
      'Scandinavische en Britse expats (grootste community op Costa del Sol)',
      'Jonge kopers of gezinnen met een kleiner budget',
      'Investeerders die hoge bezettingsgraad voor verhuur zoeken',
      'Pendelaars naar Málaga: trein in 25 min naar centrum',
    ],
    prijsniveau: {
      segment: 'midden (betaalbaar vergeleken met Marbella)',
      prijs_per_m2_range: '€3.000 – €5.000/m²',
      typisch_appartement: '€180.000 – €500.000',
      typische_villa: '€500.000 – €2.000.000',
      toelichting: 'Gemiddeld €4.301/m² (augustus 2025, +18% j/j). Significant goedkoper dan Marbella maar stijgend. Stadcentrum appartementen zijn het duurste; randwijken en Torreblanca goedkoper.',
    },
    troeven: [
      'Trein naar Málaga centrum en airport in 20–25 min: ideaal voor pendelaars',
      'Alles op wandelafstand: supermarkten, horeca, strand, winkels',
      'Groot Scandinavisch en internationaal netwerk: altijd mensen om mee te spreken',
      'Lagere prijzen dan Marbella met vergelijkbare strandkwaliteit',
      'Jaarround actief: geen "dood" buiten het seizoen',
      'Dierentuin Bioparc Fuengirola: populaire toeristische trekpleister',
    ],
    aandachtspunten: [
      'Drukkiger en stedelijker dan andere kustplaatsen: niet geschikt voor rustzoekers',
      'Weinig nieuwbouwaanbod in centrum: beperkte beschikbaarheid nieuwe projecten',
      'Minder prestigieus imago dan Marbella of Estepona',
    ],
    verhuurpotentieel: 'Uitstekend: hoge bezetting door centrumligging en bekendheid. Appartementen strand €1.000–€2.500/week in zomer. Jarenlange verhuurrendementen 5–7% bruto. Sterkste langetermijnhuurmarkt van de oostelijke Costa door grote expat-gemeenschap.',
    infrastructuur: 'Uitstekend: volledig uitgeruste stad. Alles aanwezig: El Corte Inglés Miramar Shopping, Mercadona, internationale restaurants, medisch centrum, ziekenhuis Costa del Sol op 15 min (Marbella), treinstation, busstation, directe strandverbinding.',
  },

  benalmadena: {
    name: 'Benalmádena',
    slug: 'benalmadena',
    karakter: 'Benalmádena bestaat eigenlijk uit drie sferen: Benalmádena Costa (drukke kuststrip met casino, strand clubs en jachthaven), Benalmádena Pueblo (pittoresk wit dorp op de heuvel) en Arroyo de la Miel (echte stadskern met Spaanse inwoners). De jachthaven Puerto Marina is een van de mooiste van Spanje. Het is een bruisend, toeristisch maar ook residentieel gebied met goede infrastructuur. Tivoli World amusement park (gesloten 2020) opent opnieuw met een €100–200M investering, wat de omgeving verder opwaardeert.',
    ligging: {
      malaga_airport_km: 18,
      malaga_airport_min: 15,
      marbella_centrum_km: 42,
      marbella_centrum_min: 40,
      strand_min: '2–10 minuten',
      golf: 'Torrequebrada Golf op 5 min; Lauro Golf op 15 min',
      bijzonderheden: 'Treinstation: Málaga centrum op 20 min; teleférico (kabelbaan) omhoog naar Calamorro',
    },
    doelgroep: [
      'Kopers die vlakbij Málaga airport willen zijn (15 min)',
      'Toeristen/investeerders die verhuurrendement zoeken in drukbezet gebied',
      'Gezinnen die stadsleven combineren met strand en natuur',
      'Scandinavisch en Brits publiek dat al bekende kustinfrastructuur wil',
    ],
    prijsniveau: {
      segment: 'midden',
      prijs_per_m2_range: '€3.000 – €5.000/m²',
      typisch_appartement: '€200.000 – €600.000',
      typische_villa: '€500.000 – €2.000.000',
      toelichting: 'Gemiddeld €4.284/m² (2025, +8,6% j/j). 20–30% goedkoper dan Marbella met gelijke strandkwaliteit. Sterke groeikatalysator: herope­ning Tivoli World verwacht 2026–2027.',
    },
    troeven: [
      'Dichtstbij Málaga airport van de bewoonbare kuststrook: slechts 15 min',
      'Puerto Marina: een van de mooiste jachthavens van Spanje',
      'Treinverbinding naar Málaga centrum in 20 min',
      'Kabelbaan (teleférico) naar Calamorro: panoramisch uitzicht tot Afrika',
      'Tivoli World heropening: grote investering in toeristische aantrekking',
      '20–30% goedkoper dan Marbella met vergelijkbare kwaliteit',
    ],
    aandachtspunten: [
      'Toeristisch en druk in hoogseizoen — niet voor rustzoekers',
      'Verder van Marbella dan Fuengirola of Mijas (40 min)',
      'Sommige kustgedeeltes zijn sterk commercieel en minder exclusief van karakter',
    ],
    verhuurpotentieel: 'Uitstekend: een van de populairste verhuurgebieden door toeristenstroom. Appartementen €900–€2.500/week. Hoog bezettingsgraad van april tot oktober. Bruto rendement 5–8%.',
    infrastructuur: 'Uitstekend: Carrefour, Mercadona, diverse restaurants, bars, casino, watersportcentrum, aquapark, El Corte Inglés vlakbij (Torremolinos), treinstation Arroyo de la Miel, medisch centrum.',
  },

  ojen: {
    name: 'Ojén',
    slug: 'ojen',
    karakter: 'Ojén is een schilderachtig wit bergdorp verscholen in de Sierra de las Nieves, op slechts 10 km van Marbella. Het combineert absolute rust en natuur met verrassende nabijheid van Marbella\'s luxe. De weg omhoog is spectaculair met panoramische zeezichten. Rondom het dorp liggen enkele exclusieve resorts (Palo Alto, La Mairena, El Soto de Marbella) die het imago van luxe landhuis met clubhuis-leven belichamen. Het is een insider-keuze voor mensen die het beste van twee werelden willen: natuur én marbella-comfort op 10 min.',
    ligging: {
      malaga_airport_km: 65,
      malaga_airport_min: 50,
      marbella_centrum_km: 10,
      marbella_centrum_min: 20,
      strand_min: '20–30 minuten via Marbella',
      golf: 'El Madroñal en La Cañada op 15 min; Golf Valley Nueva Andalucía op 20 min',
      bijzonderheden: 'Gelegen op 200m hoogte; frissere temperaturen in zomer; beschermd gebied Sierra de las Nieves',
    },
    doelgroep: [
      'Kopers die Marbella-nabijheid willen maar absolute rust en natuur verkiezen',
      'Mensen die een country club/resort lifestyle willen (Palo Alto, La Mairena)',
      'Second home kopers die de warmte in zomer ontlopen (frissere bergen)',
      'Architectuur-liefhebbers: Palo Alto Resort is bekroond design',
    ],
    prijsniveau: {
      segment: 'midden tot luxe',
      prijs_per_m2_range: '€3.000 – €6.500/m²',
      typisch_appartement: '€300.000 – €900.000',
      typische_villa: '€800.000 – €5.000.000',
      toelichting: 'Gemiddeld €3.838/m² (2025) — de 6e duurste gemeente van Málaga. Goedkoper dan Marbella centrum maar stijgend. Palo Alto (bekroond resort) heeft hogere prijzen. Beperkt aanbod houdt prijs stabiel.',
    },
    troeven: [
      'Slechts 10 km / 20 min van Marbella centrum en Puerto Banús',
      'Palo Alto Resort: bekroond architecturaal luxe resort met club en faciliteiten',
      'Absolute rust en privacy in natuur van Sierra de las Nieves (UNESCO biosfeerreservaat)',
      'Frissere temperaturen in zomer dan aan de kust',
      'Spectaculaire panoramische uitzichten over zee en bergen',
      'Groeiend als premium alternatief voor Marbella-kopers die meer ruimte zoeken',
    ],
    aandachtspunten: [
      'Strand is 20–30 min rijden: dagelijks strand bezoeken is minder praktisch',
      'Auto absoluut noodzakelijk: geen openbaar vervoer omhoog',
      'Beperkte eigen voorzieningen in het dorp: bakkerij, bar, klein supermarktje — alles verder in Marbella',
    ],
    verhuurpotentieel: 'Niche maar stijgend. Luxe villa\'s in Palo Alto/La Mairena verhuren voor €3.000–€10.000/week. Grotere aantrekkingskracht bij kopers van rust en natuur dan bij massa-toeristen.',
    infrastructuur: 'Beperkt in het dorp zelf. Palo Alto en La Mairena resorts hebben eigen voorzieningen (clubhuis, zwembad, fitness). Marbella op 20 min voor alle andere diensten. Ziekenhuis Quirónsalud Marbella op 25 min.',
  },

  istan: {
    name: 'Istán',
    slug: 'istan',
    karakter: 'Istán is Marbella\'s best bewaarde geheim: een klein authentiek wit bergdorp op de rand van een kunstmatig meer (Embalse de la Concepción), omringd door het Sierra de las Nieves-reservaat. Het meer schittert turquoise blauw in het groen en het uitzicht is adembenemend. Slechts 10 min van Puerto Banús maar een ander wereld: volkomen rustig, geen massa-toerisme, kleine gemeenschap, pure natuur. Ideaal voor wie écht tot rust wil komen maar toch dicht bij alles wil wonen.',
    ligging: {
      malaga_airport_km: 68,
      malaga_airport_min: 55,
      marbella_centrum_km: 13,
      marbella_centrum_min: 20,
      puerto_banus_km: 8,
      puerto_banus_min: 10,
      strand_min: '15–20 minuten via Puerto Banús',
      golf: 'Golf Valley Nueva Andalucía op 15 min',
      bijzonderheden: 'Beschermd gebied: beperkte bouwmogelijkheden houden prijzen stabiel en aanbod schaars',
    },
    doelgroep: [
      'Natuur- en rustliefhebbers die dichtbij Marbella willen wonen',
      'Exclusieve kopers die absoluut privacy en unieke omgeving zoeken',
      'Kopers die willen ontsnappen aan de warmte (berg: 3–5°C koeler in zomer)',
      'Tweede verblijf voor Marbella-kopers die ook natuur willen hebben',
    ],
    prijsniveau: {
      segment: 'luxe (beperkt aanbod = hoge prijzen)',
      prijs_per_m2_range: '€3.500 – €7.000/m²',
      typisch_appartement: '€400.000 – €1.000.000',
      typische_villa: '€1.000.000 – €6.000.000',
      toelichting: 'Aanbod is uiterst beperkt door beschermde status. Wat er is, is exclusief en houdt zijn waarde uitstekend. Prijzen stijgen stabiel door schaarste. Geen massaproductie van nieuwbouw mogelijk.',
    },
    troeven: [
      'Embalse de la Concepción: spectaculair meer direct aan het dorp',
      'Slechts 10 min van Puerto Banús en 20 min van Marbella centrum',
      'Volkomen authentiek: geen toeristische ontwikkeling, geen hordes dagjesmensen',
      'UNESCO biosfeerreservaat Sierra de las Nieves: wandelen, fietsen, wilde natuur',
      'Frissere berglucht in zomer',
      'Schaars aanbod = stabiele waarde, geen overaanbod ooit',
    ],
    aandachtspunten: [
      'Strand is 15–20 min rijden: niet voor dagelijks strandbezoek',
      'Heel beperkt aanbod nieuwbouw: wanneer er iets beschikbaar is, is snel verkocht',
      'Praktisch geen eigen winkels of restaurants: alles halen in Marbella of Puerto Banús',
    ],
    verhuurpotentieel: 'Niche maar sterke premium markt. Luxe villa\'s met meer- of bergzicht €3.000–€15.000/week. Aangetroken door "digital nomad" type en stille luxe-reizigers. Beperkte maar constante vraag.',
    infrastructuur: 'Minimaal ter plaatse: klein dorp met bar, kerkje, basiswinkeltje. Alles op 10–20 min in Puerto Banús of Marbella. Geen eigen medische post; dichtstbijzijnde ziekenhuis Marbella (20 min).',
  },
};

module.exports = { AREAS };
